# Generated by Django 5.0.7 on 2024-07-22 18:44

import Post.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Descrp', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Img', Post.models.CloudinaryField(max_length=255, verbose_name='Post')),
                ('Aww', models.IntegerField(default=0)),
                ('Eww', models.IntegerField(default=0)),
                ('op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Points', models.IntegerField(default=1)),
                ('comment', models.TextField(max_length=500)),
                ('reply', models.CharField(default='0', max_length=1)),
                ('cmnt_chn', models.CharField(default='1', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('not_post_method_ok', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
    ]
